//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeEnvironmentLifePlanner.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeEnvironmentLifePlanner.Client.Properties.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akronim jest wymagany!.
        /// </summary>
        public static string sharedAcronymRequired {
            get {
                return ResourceManager.GetString("sharedAcronymRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string sharedCancel {
            get {
                return ResourceManager.GetString("sharedCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        public static string sharedCreate {
            get {
                return ResourceManager.GetString("sharedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć.
        /// </summary>
        public static string sharedDeleteConfimation {
            get {
                return ResourceManager.GetString("sharedDeleteConfimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć grupy- istnieje conajmniej jeden podrzędny element lub grupa!.
        /// </summary>
        public static string sharedDeleteExistsChild {
            get {
                return ResourceManager.GetString("sharedDeleteExistsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć głównej grupy.
        /// </summary>
        public static string sharedDeleteHeadParent {
            get {
                return ResourceManager.GetString("sharedDeleteHeadParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie usunięto.
        /// </summary>
        public static string sharedDeleteOk {
            get {
                return ResourceManager.GetString("sharedDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trwa ładowanie . . ..
        /// </summary>
        public static string sharedLoading {
            get {
                return ResourceManager.GetString("sharedLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jest wymagana!.
        /// </summary>
        public static string sharedNameRequired {
            get {
                return ResourceManager.GetString("sharedNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak danych!.
        /// </summary>
        public static string sharedNoRecords {
            get {
                return ResourceManager.GetString("sharedNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer referencyjny jest wymagany.
        /// </summary>
        public static string sharedReferenceNumberRequired {
            get {
                return ResourceManager.GetString("sharedReferenceNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string sharedSave {
            get {
                return ResourceManager.GetString("sharedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie zaaktualizowano.
        /// </summary>
        public static string sharedUpdateOk {
            get {
                return ResourceManager.GetString("sharedUpdateOk", resourceCulture);
            }
        }
    }
}
